### ISSUE TITLE
I need to print the territory cards with Google Maps

### ISSUE THREAD

**Issue by h0W13r** [luontola/territory-bro#34]

**Comment by luontola** [comment]
Google Maps' terms of service presumably prevent using them, because Territory Bro uses also other maps.

Quoted from https://cloud.google.com/maps-platform/terms/
> (e) *No Use With Non-Google Maps.* To avoid quality issues and/or brand confusion, Customer will not use the Google Maps Core Services with or near a non-Google Map in a Customer Application. For example, Customer will not (i) display or use Places content on a non-Google map, (ii) display Street View imagery and non-Google maps on the same screen, or (iii) link a Google Map to non-Google Maps content or a non-Google map.

Also AFAIK, Google Maps requires the use of their own SDK and cannot be integrated with OpenLayers, so maintaining two map implementations would be a huge burden.
